import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.39.0'

interface RedeemCodeRequest {
  code: string
  device_name: string
}

interface RedeemCodeResponse {
  success: boolean
  error?: string
  student_id?: string
  device_id?: string
}

/**
 * Edge Function: Redeem Device Link Code
 *
 * Purpose:
 * - Validate a one-time device link code generated by the parent in the admin panel
 * - Link the calling device's own anonymous auth session to the student profile
 * - Mark the code as used
 *
 * Flow (fixed 2026-09-15 — see "Rewritten" note below):
 * 1. Parent generates code via admin panel
 * 2. Parent shows code to child
 * 3. Child's client calls `supabase.auth.signInAnonymously()` itself, getting
 *    a real session (access/refresh tokens) it can persist and reuse
 * 4. Client calls this function WITH that session's JWT (Authorization header)
 *    + { code, device_name }
 * 5. Function verifies the JWT, validates the code, and links auth.uid() (the
 *    caller's own anonymous user) to the student via `student_devices`
 * 6. Client already holds its own session — no token needs to be handed back
 *
 * Rewritten 2026-09-15: the original version created a *separate* auth user
 * server-side via `auth.admin.createUser()` and never actually returned
 * usable session credentials for it (the `generateLink` call at the end
 * produced a magic-link token for an email the user has no way to receive,
 * not a session) — a dead end that would have blocked every device link
 * attempt. Standard Supabase anonymous auth (client-side `signInAnonymously`)
 * fixes this: the client gets a real session immediately, and this function
 * only needs to *link* that already-authenticated anonymous user to a
 * student, which needs the service role key only because `student_devices`
 * has no RLS policy permitting a fresh anonymous user to insert its own row
 * (by design — see DATABASE_SCHEMA.md §4 policy matrix).
 *
 * Security Notes:
 * - Codes expire after 48 hours by default (set by parent when generating)
 * - Codes can only be used once
 * - This function runs server-side with the service role key ONLY for the
 *   student_devices insert / device_link_codes update; auth.uid() comes
 *   from the caller's own verified JWT, not from anything client-supplied
 * - Students never see the parent's data (RLS protects this)
 * - Idempotent: if this exact anonymous session already has a linked,
 *   non-revoked device, re-calling this function (e.g. a page reload right
 *   after linking) returns the existing link instead of erroring
 *
 * The handler MUST be registered with `Deno.serve(...)`. Until 2026-09-24
 * it was `export default async (req) => ...`, which the Supabase Edge
 * Runtime does not recognise: the module booted, no handler was ever
 * attached, and every request (even an OPTIONS preflight) hung with zero
 * response bytes until the worker was reaped. That hang was blamed on the
 * cloud sandbox's proxy and on verify_jwt for over a week; neither was the
 * cause. It reproduced identically from a normal Windows machine, while a
 * `Deno.serve` hello-world on the same project answered instantly.
 *
 * Deployed with verify_jwt = false (`--no-verify-jwt`, per
 * docs/runbooks/verify-play-harness.md). This function authenticates the
 * caller itself: it requires the Authorization header and resolves the
 * user with `callerClient.auth.getUser()` before doing anything privileged.
 *
 * Reference: DATABASE_SCHEMA.md §3.5 (device_link_codes), §3.6 (student_devices)
 */

// CORS: this function is called directly from the browser (supabase-js
// `functions.invoke`), which sends an OPTIONS preflight first because the
// request carries an Authorization header.
const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
}

Deno.serve(async (req: Request): Promise<Response> => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    if (req.method !== 'POST') {
      return jsonResponse({ success: false, error: 'Method not allowed' }, 405)
    }

    const authHeader = req.headers.get('Authorization')
    if (!authHeader) {
      return jsonResponse(
        { success: false, error: 'Missing Authorization header — call supabase.auth.signInAnonymously() first' },
        401
      )
    }

    const body = (await req.json()) as RedeemCodeRequest
    if (!body.code || !body.device_name) {
      return jsonResponse({ success: false, error: 'Missing code or device_name' }, 400)
    }

    const supabaseUrl = Deno.env.get('SUPABASE_URL')
    const supabaseAnonKey = Deno.env.get('SUPABASE_ANON_KEY')
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')

    if (!supabaseUrl || !supabaseAnonKey || !supabaseServiceKey) {
      return jsonResponse({ success: false, error: 'Missing environment variables' }, 500)
    }

    // Resolve the caller's own uid from their forwarded JWT (their anonymous session)
    const callerClient = createClient(supabaseUrl, supabaseAnonKey, {
      auth: { persistSession: false },
      global: { headers: { Authorization: authHeader } },
    })
    const {
      data: { user },
      error: userError,
    } = await callerClient.auth.getUser()

    if (userError || !user) {
      return jsonResponse({ success: false, error: 'Not authenticated' }, 401)
    }

    // Service role client: needed because student_devices has no RLS policy
    // letting a fresh anonymous user insert its own row (by design)
    const admin = createClient(supabaseUrl, supabaseServiceKey, { auth: { persistSession: false } })

    // Idempotency: if this device is already linked, just return that link
    // rather than erroring on a re-call (e.g. a page reload).
    const { data: existingDevice } = await admin
      .from('student_devices')
      .select('id, student_id')
      .eq('auth_user_id', user.id)
      .is('revoked_at', null)
      .maybeSingle()

    if (existingDevice) {
      return jsonResponse({ success: true, student_id: existingDevice.student_id, device_id: existingDevice.id }, 200)
    }

    // Step 1: find and validate the device link code
    const { data: codeData, error: codeError } = await admin
      .from('device_link_codes')
      .select('id, student_id, expires_at, used_at')
      .eq('code', body.code.toUpperCase())
      .single()

    if (codeError || !codeData) {
      return jsonResponse({ success: false, error: 'Invalid code' }, 401)
    }

    // Step 2: check expiry
    if (new Date() > new Date(codeData.expires_at)) {
      return jsonResponse({ success: false, error: 'Code has expired' }, 401)
    }

    // Step 3: check already used
    if (codeData.used_at) {
      return jsonResponse({ success: false, error: 'Code has already been used' }, 401)
    }

    // Step 4: link this anonymous user to the student
    const { data: deviceData, error: deviceError } = await admin
      .from('student_devices')
      .insert({
        student_id: codeData.student_id,
        device_name: body.device_name,
        auth_user_id: user.id,
      })
      .select('id')
      .single()

    if (deviceError || !deviceData) {
      console.error('Device creation error:', deviceError)
      return jsonResponse({ success: false, error: 'Failed to link device' }, 500)
    }

    // Step 5: mark the code as used
    const { error: updateError } = await admin
      .from('device_link_codes')
      .update({ used_at: new Date().toISOString() })
      .eq('id', codeData.id)

    if (updateError) {
      console.error('Code update error:', updateError)
      // Not fatal — the device is already linked; this is just record-keeping
    }

    return jsonResponse({ success: true, student_id: codeData.student_id, device_id: deviceData.id }, 200)
  } catch (error) {
    console.error('Unexpected error:', error)
    return jsonResponse({ success: false, error: 'Internal server error' }, 500)
  }
})

function jsonResponse(body: RedeemCodeResponse, status: number): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { 'Content-Type': 'application/json', ...corsHeaders },
  })
}
